Repository soyoung125/fin-the-pen-web-v2, pull requests merged in 2023-07, with the labels that each got.

#2 docs: 리드미 생성
  readme.md
Labels: documentation

#8 리드미를 최신화한다
  readme.md
  src/App.tsx
Labels: documentation

#11 feat: testtesttest
  readme.md
Labels: help wanted, question

#15 feat: Layout 구현
  src/app/router.tsx
  src/assets/logos/logo_white.png
  src/components/common/RoundedButton.tsx
  src/components/common/SwitchingHeader.tsx
  src/components/layouts/containerLayout/AnalysisLayout.tsx
  src/components/layouts/containerLayout/HomeLayout.tsx
  src/components/layouts/containerLayout/ManagementLayout.tsx
  src/containers/analysis/AnalysisHeader/index.tsx
  src/containers/home/common/BottomBar.tsx
  src/containers/home/common/TopBar/buttons/FilterButton/index.tsx
  src/containers/home/common/TopBar/buttons/LogoButton.tsx
  src/containers/home/common/TopBar/buttons/PersonalButton.tsx
  src/containers/home/common/TopBar/buttons/PopupButton.tsx
  src/containers/home/common/TopBar/headerMode/AnalysisMode.tsx
  src/containers/home/common/TopBar/headerMode/HomeMode.tsx
  src/containers/home/common/TopBar/index.tsx
  src/domain/constants/managements.tsx
Labels: 기능

#17 fix: 배포 시 새로고침이 안되는 문제 수정
  index.html
  public/404.html
Labels: 버그

#19 chore: recoil을 설치한다
  package.json
  src/main.tsx
  yarn.lock
Labels: 유지보수 및 설정
